// <auto-generated />
using System;
using ITEquipmentInventory.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ITEquipmentInventory.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625081712_ChangeEquipemtANDEquimentreturn")]
    partial class ChangeEquipemtANDEquimentreturn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("ITEquipmentInventory.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkerCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.HasIndex("WorkerCode")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ITEquipmentInventory.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CurrentEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CurrentSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandedOverBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrentEmployeeId");

                    b.HasIndex("CurrentSiteId");

                    b.HasIndex("InventoryNumber")
                        .IsUnique();

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ITEquipmentInventory.Models.EquipmentReturn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HandedOverBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousEmployeeCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousEmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousEmployeeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousHandedOverBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSiteCode")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PreviousSiteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PreviousSiteLocation")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousSiteName")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviousStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReturnedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EquipmentReturns");
                });

            modelBuilder.Entity("ITEquipmentInventory.Models.Site", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Sites");
                });

            modelBuilder.Entity("ITEquipmentInventory.Models.Employee", b =>
                {
                    b.HasOne("ITEquipmentInventory.Models.Site", "Site")
                        .WithMany("Employees")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");
                });

            modelBuilder.Entity("ITEquipmentInventory.Models.Equipment", b =>
                {
                    b.HasOne("ITEquipmentInventory.Models.Employee", "CurrentEmployee")
                        .WithMany()
                        .HasForeignKey("CurrentEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ITEquipmentInventory.Models.Site", "CurrentSite")
                        .WithMany("EquipmentItems")
                        .HasForeignKey("CurrentSiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrentEmployee");

                    b.Navigation("CurrentSite");
                });

            modelBuilder.Entity("ITEquipmentInventory.Models.Site", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("EquipmentItems");
                });
#pragma warning restore 612, 618
        }
    }
}
